### PR TITLE
Please Allow authoritative config so servers can impose config settin…

### PR DESCRIPTION
**Pull request by sbtoonz**
…gs on clients.

### CODE REVIEW

**Comment by sbtoonz** [comment]
Fixed Requirement check to not use MCE as it is a poor solution. @aedenthorn

**Comment by sbtoonz** [comment]
I can just go through all these and add server sync if you want.... haha it doesn't look like you'll ever acknowledge the PR tho

**Comment by aedenthorn** [comment]
Thanks, that looks like a better option

**Comment by sbtoonz** [comment]
https://github.com/blaxxun-boop/ServerSync

**Comment by aedenthorn** [comment]
why did you do something different for DeathTweaks? I don't quite understand what the two are doing differently

**Comment by sbtoonz** [comment]
> why did you do something different for DeathTweaks? I don't quite understand what the two are doing differently

I had used auto config before blaxun made her server sync code public. Once she made it public I opted to move to a better option. I should have removed the auth server sync files for DT I can give an updated Pr for that one

**Comment by sbtoonz** [comment]
Yah I realized that I hadn't revisited DT with updated ServerSync and it was still on AuthConfig setup (which works fine just a little chatty in the log and no live update or cfg lock) 
I will issue updated PR for that one

**Pull request merged**
