### PR TITLE
Add support for CargoCrates in AutoFuel

### PR DESCRIPTION
**Pull request by Stealthii**
CargoCrates are the prefabs spawned by carts, boats, etc. when destroyed. This change allows them to be considered as containers by AutoFuel, if the config option "AllowCargoCrates" is enabled.

Part of this change includes more specific detection of chests vs. cargo crates on their specified layers.

### CODE REVIEW

**Comment by aedenthorn** [comment]
Does this find containers named Container? Like in ships and carts?

**Comment by Stealthii** [comment]
Nope - I only added support for dropped cargo crates in this PR, as they are a common decorative item used in bases. Vehicles are doable, but ideally more changes / configurability are needed to make that work in a way people would be happy with.

For example, do vehicles refuel when parked/unparked - example case would be someone wanting to refuel torches from a cart they are running along a bridge with (unparked), or wanting a ship to unload only when uncontrolled (parked)

**Comment by Stealthii** [comment]
This PR has been updated to fix conflicts with the latest changes.

**Comment by aedenthorn** [comment]
This still doesn't allow for containers named Container afaics

**Pull request merged**
